version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/bankmanager
    depends_on:
      - db
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: bankmanager
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD:-}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_DATABASE: bankmanager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
    depends_on:
      - db

volumes:
  db_data: